# docker/docker-compose.yml
version: '3'

services:
    database:
        image: mariadb:latest
        container_name: refly_database_${APP_INSTANCE}
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        ports:
            - ${DATABASE_PORT}:3306
        volumes:
            - ./data/backup:/db
        env_file:
            - .env.local
        logging:
            driver: json-file

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: refly_phpmyadmin_${APP_INSTANCE}
        restart: unless-stopped
        depends_on:
            - database
        links:
            - database:database
        ports:
            - ${PHPMYADMIN_PORT}:80
        environment:
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - PMA_HOST=database
            - PMA_USER=root
            - PMA_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - UPLOAD_LIMIT=100000000

    php:
        build: .docker/
        container_name: refly_php_${APP_INSTANCE}
        restart: unless-stopped
        depends_on:
            - database
        links:
            - database
#            - mail_dev
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        volumes:
#            - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
            - ./:/var/www
        env_file:
            - .env
            - .env.local
        logging:
            driver: "json-file"

    mail_dev:
        image: djfarrelly/maildev
        container_name: refly_maildev_${APP_INSTANCE}
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - ${SMTP_PORT}:80
        restart: unless-stopped

    nginx:
        build:
            context: .docker/nginx
        container_name: refly_nginx_${APP_INSTANCE}
        restart: unless-stopped
        links:
            - mail_dev
            - phpmyadmin
            - database
        volumes:
            - ./:/var/www
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - .docker/nginx/sites/:/etc/nginx/sites-available
            - .docker/nginx/conf.d/:/etc/nginx/conf.d
#            - .docker/nginx/log:/var/log
        depends_on:
            - php
        env_file:
            - .env
            - .env.local
        ports:
            - ${APP_PORT}:8080
            - "443:443"
        logging:
            driver: json-file